# Dependabot configuration for automated dependency updates
# Helps keep dependencies secure and up-to-date

version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-team-name" # Replace with your team/username
    assignees:
      - "your-team-name" # Replace with your team/username
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    # Group minor and patch updates together
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    # Security updates are always separate PRs
    ignore:
      # Ignore major version updates (review these manually)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "ci"
      - "dependencies"
