/**
 * Holiday Calendar (2025-2030)
 * Generated by scripts/generate-holidays.js
 * 
 * Sources:
 * - Malaysia: https://publicholidays.com.my/
 * - Singapore: https://www.mom.gov.sg/employment-practices/public-holidays
 * - Vietnam: https://publicholidays.vn/
 */

export interface Holiday {
  date: string; // ISO format YYYY-MM-DD
  name: string;
}

export interface HolidayCalendar {
  name: string;
  holidays: Holiday[];
}

export const HOLIDAYS: Record<'ABMY' | 'ABSG' | 'ABVN', HolidayCalendar> = {
  "ABMY": {
    "name": "Malaysia",
    "holidays": [
      {
        "date": "2025-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2025-01-25",
        "name": "Thaipusam"
      },
      {
        "date": "2025-01-29",
        "name": "Chinese New Year"
      },
      {
        "date": "2025-01-30",
        "name": "Chinese New Year"
      },
      {
        "date": "2025-03-31",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2025-04-01",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2025-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2025-05-12",
        "name": "Vesak Day"
      },
      {
        "date": "2025-06-02",
        "name": "Agong's Birthday"
      },
      {
        "date": "2025-06-07",
        "name": "Hari Raya Aidiladha"
      },
      {
        "date": "2025-06-28",
        "name": "Awal Muharram"
      },
      {
        "date": "2025-08-31",
        "name": "National Day"
      },
      {
        "date": "2025-09-06",
        "name": "Maulidur Rasul"
      },
      {
        "date": "2025-09-16",
        "name": "Malaysia Day"
      },
      {
        "date": "2025-10-24",
        "name": "Deepavali"
      },
      {
        "date": "2025-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2026-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2026-01-14",
        "name": "Thaipusam"
      },
      {
        "date": "2026-02-17",
        "name": "Chinese New Year"
      },
      {
        "date": "2026-02-18",
        "name": "Chinese New Year"
      },
      {
        "date": "2026-03-21",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2026-03-22",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2026-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2026-05-01",
        "name": "Vesak Day"
      },
      {
        "date": "2026-05-28",
        "name": "Hari Raya Aidiladha"
      },
      {
        "date": "2026-06-06",
        "name": "Agong's Birthday"
      },
      {
        "date": "2026-06-17",
        "name": "Awal Muharram"
      },
      {
        "date": "2026-08-25",
        "name": "Maulidur Rasul"
      },
      {
        "date": "2026-08-31",
        "name": "National Day"
      },
      {
        "date": "2026-09-16",
        "name": "Malaysia Day"
      },
      {
        "date": "2026-10-13",
        "name": "Deepavali"
      },
      {
        "date": "2026-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2027-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2027-02-03",
        "name": "Thaipusam"
      },
      {
        "date": "2027-02-06",
        "name": "Chinese New Year"
      },
      {
        "date": "2027-02-07",
        "name": "Chinese New Year"
      },
      {
        "date": "2027-03-10",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2027-03-11",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2027-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2027-05-17",
        "name": "Hari Raya Aidiladha"
      },
      {
        "date": "2027-05-20",
        "name": "Vesak Day"
      },
      {
        "date": "2027-06-05",
        "name": "Agong's Birthday"
      },
      {
        "date": "2027-06-06",
        "name": "Awal Muharram"
      },
      {
        "date": "2027-08-14",
        "name": "Maulidur Rasul"
      },
      {
        "date": "2027-08-31",
        "name": "National Day"
      },
      {
        "date": "2027-09-16",
        "name": "Malaysia Day"
      },
      {
        "date": "2027-11-02",
        "name": "Deepavali"
      },
      {
        "date": "2027-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2028-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2028-01-24",
        "name": "Thaipusam"
      },
      {
        "date": "2028-01-26",
        "name": "Chinese New Year"
      },
      {
        "date": "2028-01-27",
        "name": "Chinese New Year"
      },
      {
        "date": "2028-02-27",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2028-02-28",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2028-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2028-05-06",
        "name": "Hari Raya Aidiladha"
      },
      {
        "date": "2028-05-08",
        "name": "Vesak Day"
      },
      {
        "date": "2028-05-27",
        "name": "Awal Muharram"
      },
      {
        "date": "2028-06-05",
        "name": "Agong's Birthday"
      },
      {
        "date": "2028-08-03",
        "name": "Maulidur Rasul"
      },
      {
        "date": "2028-08-31",
        "name": "National Day"
      },
      {
        "date": "2028-09-16",
        "name": "Malaysia Day"
      },
      {
        "date": "2028-10-21",
        "name": "Deepavali"
      },
      {
        "date": "2028-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2029-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2029-01-13",
        "name": "Thaipusam"
      },
      {
        "date": "2029-02-13",
        "name": "Chinese New Year"
      },
      {
        "date": "2029-02-14",
        "name": "Chinese New Year"
      },
      {
        "date": "2029-02-16",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2029-02-17",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2029-04-25",
        "name": "Hari Raya Aidiladha"
      },
      {
        "date": "2029-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2029-05-16",
        "name": "Awal Muharram"
      },
      {
        "date": "2029-05-27",
        "name": "Vesak Day"
      },
      {
        "date": "2029-06-04",
        "name": "Agong's Birthday"
      },
      {
        "date": "2029-07-24",
        "name": "Maulidur Rasul"
      },
      {
        "date": "2029-08-31",
        "name": "National Day"
      },
      {
        "date": "2029-09-16",
        "name": "Malaysia Day"
      },
      {
        "date": "2029-10-09",
        "name": "Deepavali"
      },
      {
        "date": "2029-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2030-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2030-02-01",
        "name": "Thaipusam"
      },
      {
        "date": "2030-02-03",
        "name": "Chinese New Year"
      },
      {
        "date": "2030-02-04",
        "name": "Chinese New Year"
      },
      {
        "date": "2030-02-06",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2030-02-07",
        "name": "Hari Raya Aidilfitri"
      },
      {
        "date": "2030-04-15",
        "name": "Hari Raya Aidiladha"
      },
      {
        "date": "2030-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2030-05-05",
        "name": "Awal Muharram"
      },
      {
        "date": "2030-05-16",
        "name": "Vesak Day"
      },
      {
        "date": "2030-06-01",
        "name": "Agong's Birthday"
      },
      {
        "date": "2030-07-13",
        "name": "Maulidur Rasul"
      },
      {
        "date": "2030-08-31",
        "name": "National Day"
      },
      {
        "date": "2030-09-16",
        "name": "Malaysia Day"
      },
      {
        "date": "2030-10-28",
        "name": "Deepavali"
      },
      {
        "date": "2030-12-25",
        "name": "Christmas Day"
      }
    ]
  },
  "ABSG": {
    "name": "Singapore",
    "holidays": [
      {
        "date": "2025-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2025-01-29",
        "name": "Chinese New Year"
      },
      {
        "date": "2025-01-30",
        "name": "Chinese New Year"
      },
      {
        "date": "2025-03-31",
        "name": "Hari Raya Puasa"
      },
      {
        "date": "2025-04-18",
        "name": "Good Friday"
      },
      {
        "date": "2025-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2025-05-12",
        "name": "Vesak Day"
      },
      {
        "date": "2025-06-07",
        "name": "Hari Raya Haji"
      },
      {
        "date": "2025-08-09",
        "name": "National Day"
      },
      {
        "date": "2025-10-20",
        "name": "Deepavali"
      },
      {
        "date": "2025-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2026-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2026-02-17",
        "name": "Chinese New Year"
      },
      {
        "date": "2026-02-18",
        "name": "Chinese New Year"
      },
      {
        "date": "2026-03-21",
        "name": "Hari Raya Puasa"
      },
      {
        "date": "2026-04-03",
        "name": "Good Friday"
      },
      {
        "date": "2026-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2026-05-01",
        "name": "Vesak Day"
      },
      {
        "date": "2026-05-28",
        "name": "Hari Raya Haji"
      },
      {
        "date": "2026-08-09",
        "name": "National Day"
      },
      {
        "date": "2026-10-09",
        "name": "Deepavali"
      },
      {
        "date": "2026-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2027-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2027-02-06",
        "name": "Chinese New Year"
      },
      {
        "date": "2027-02-07",
        "name": "Chinese New Year"
      },
      {
        "date": "2027-03-10",
        "name": "Hari Raya Puasa"
      },
      {
        "date": "2027-03-26",
        "name": "Good Friday"
      },
      {
        "date": "2027-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2027-05-17",
        "name": "Hari Raya Haji"
      },
      {
        "date": "2027-05-20",
        "name": "Vesak Day"
      },
      {
        "date": "2027-08-09",
        "name": "National Day"
      },
      {
        "date": "2027-10-29",
        "name": "Deepavali"
      },
      {
        "date": "2027-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2028-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2028-01-26",
        "name": "Chinese New Year"
      },
      {
        "date": "2028-01-27",
        "name": "Chinese New Year"
      },
      {
        "date": "2028-02-27",
        "name": "Hari Raya Puasa"
      },
      {
        "date": "2028-04-14",
        "name": "Good Friday"
      },
      {
        "date": "2028-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2028-05-06",
        "name": "Hari Raya Haji"
      },
      {
        "date": "2028-05-08",
        "name": "Vesak Day"
      },
      {
        "date": "2028-08-09",
        "name": "National Day"
      },
      {
        "date": "2028-10-17",
        "name": "Deepavali"
      },
      {
        "date": "2028-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2029-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2029-02-13",
        "name": "Chinese New Year"
      },
      {
        "date": "2029-02-14",
        "name": "Chinese New Year"
      },
      {
        "date": "2029-02-16",
        "name": "Hari Raya Puasa"
      },
      {
        "date": "2029-03-30",
        "name": "Good Friday"
      },
      {
        "date": "2029-04-25",
        "name": "Hari Raya Haji"
      },
      {
        "date": "2029-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2029-05-27",
        "name": "Vesak Day"
      },
      {
        "date": "2029-08-09",
        "name": "National Day"
      },
      {
        "date": "2029-11-06",
        "name": "Deepavali"
      },
      {
        "date": "2029-12-25",
        "name": "Christmas Day"
      },
      {
        "date": "2030-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2030-02-03",
        "name": "Chinese New Year"
      },
      {
        "date": "2030-02-04",
        "name": "Chinese New Year"
      },
      {
        "date": "2030-02-06",
        "name": "Hari Raya Puasa"
      },
      {
        "date": "2030-04-15",
        "name": "Hari Raya Haji"
      },
      {
        "date": "2030-04-19",
        "name": "Good Friday"
      },
      {
        "date": "2030-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2030-05-16",
        "name": "Vesak Day"
      },
      {
        "date": "2030-08-09",
        "name": "National Day"
      },
      {
        "date": "2030-10-26",
        "name": "Deepavali"
      },
      {
        "date": "2030-12-25",
        "name": "Christmas Day"
      }
    ]
  },
  "ABVN": {
    "name": "Vietnam",
    "holidays": [
      {
        "date": "2025-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2025-01-28",
        "name": "Lunar New Year Eve"
      },
      {
        "date": "2025-01-29",
        "name": "Lunar New Year"
      },
      {
        "date": "2025-01-30",
        "name": "Lunar New Year"
      },
      {
        "date": "2025-01-31",
        "name": "Lunar New Year"
      },
      {
        "date": "2025-02-01",
        "name": "Lunar New Year"
      },
      {
        "date": "2025-04-10",
        "name": "Hung Kings Festival"
      },
      {
        "date": "2025-04-30",
        "name": "Reunification Day"
      },
      {
        "date": "2025-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2025-09-02",
        "name": "National Day"
      },
      {
        "date": "2026-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2026-02-16",
        "name": "Lunar New Year Eve"
      },
      {
        "date": "2026-02-17",
        "name": "Lunar New Year"
      },
      {
        "date": "2026-02-18",
        "name": "Lunar New Year"
      },
      {
        "date": "2026-02-19",
        "name": "Lunar New Year"
      },
      {
        "date": "2026-02-20",
        "name": "Lunar New Year"
      },
      {
        "date": "2026-03-30",
        "name": "Hung Kings Festival"
      },
      {
        "date": "2026-04-30",
        "name": "Reunification Day"
      },
      {
        "date": "2026-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2026-09-02",
        "name": "National Day"
      },
      {
        "date": "2027-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2027-02-05",
        "name": "Lunar New Year Eve"
      },
      {
        "date": "2027-02-06",
        "name": "Lunar New Year"
      },
      {
        "date": "2027-02-07",
        "name": "Lunar New Year"
      },
      {
        "date": "2027-02-08",
        "name": "Lunar New Year"
      },
      {
        "date": "2027-02-09",
        "name": "Lunar New Year"
      },
      {
        "date": "2027-04-18",
        "name": "Hung Kings Festival"
      },
      {
        "date": "2027-04-30",
        "name": "Reunification Day"
      },
      {
        "date": "2027-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2027-09-02",
        "name": "National Day"
      },
      {
        "date": "2028-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2028-01-25",
        "name": "Lunar New Year Eve"
      },
      {
        "date": "2028-01-26",
        "name": "Lunar New Year"
      },
      {
        "date": "2028-01-27",
        "name": "Lunar New Year"
      },
      {
        "date": "2028-01-28",
        "name": "Lunar New Year"
      },
      {
        "date": "2028-01-29",
        "name": "Lunar New Year"
      },
      {
        "date": "2028-04-06",
        "name": "Hung Kings Festival"
      },
      {
        "date": "2028-04-30",
        "name": "Reunification Day"
      },
      {
        "date": "2028-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2028-09-02",
        "name": "National Day"
      },
      {
        "date": "2029-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2029-02-12",
        "name": "Lunar New Year Eve"
      },
      {
        "date": "2029-02-13",
        "name": "Lunar New Year"
      },
      {
        "date": "2029-02-14",
        "name": "Lunar New Year"
      },
      {
        "date": "2029-02-15",
        "name": "Lunar New Year"
      },
      {
        "date": "2029-02-16",
        "name": "Lunar New Year"
      },
      {
        "date": "2029-03-26",
        "name": "Hung Kings Festival"
      },
      {
        "date": "2029-04-30",
        "name": "Reunification Day"
      },
      {
        "date": "2029-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2029-09-02",
        "name": "National Day"
      },
      {
        "date": "2030-01-01",
        "name": "New Year's Day"
      },
      {
        "date": "2030-02-02",
        "name": "Lunar New Year Eve"
      },
      {
        "date": "2030-02-03",
        "name": "Lunar New Year"
      },
      {
        "date": "2030-02-04",
        "name": "Lunar New Year"
      },
      {
        "date": "2030-02-05",
        "name": "Lunar New Year"
      },
      {
        "date": "2030-02-06",
        "name": "Lunar New Year"
      },
      {
        "date": "2030-04-14",
        "name": "Hung Kings Festival"
      },
      {
        "date": "2030-04-30",
        "name": "Reunification Day"
      },
      {
        "date": "2030-05-01",
        "name": "Labour Day"
      },
      {
        "date": "2030-09-02",
        "name": "National Day"
      }
    ]
  }
};

/**
 * Check if a date is a holiday
 */
export function isHoliday(date: Date, region: 'ABMY' | 'ABSG' | 'ABVN'): boolean {
  const dateStr = date.toISOString().split('T')[0];
  return HOLIDAYS[region].holidays.some(h => h.date === dateStr);
}

/**
 * Get holiday name for a date
 */
export function getHolidayName(date: Date, region: 'ABMY' | 'ABSG' | 'ABVN'): string | null {
  const dateStr = date.toISOString().split('T')[0];
  const holiday = HOLIDAYS[region].holidays.find(h => h.date === dateStr);
  return holiday ? holiday.name : null;
}

/**
 * Get all holidays in a date range
 */
export function getHolidaysInRange(
  startDate: Date,
  endDate: Date,
  region: 'ABMY' | 'ABSG' | 'ABVN'
): Holiday[] {
  const start = startDate.toISOString().split('T')[0];
  const end = endDate.toISOString().split('T')[0];
  
  return HOLIDAYS[region].holidays.filter(h => h.date >= start && h.date <= end);
}

/**
 * Calculate working days between two dates (excludes weekends and holidays)
 */
export function calculateWorkingDays(
  startDate: Date,
  endDate: Date,
  region: 'ABMY' | 'ABSG' | 'ABVN'
): number {
  let workingDays = 0;
  const current = new Date(startDate);
  
  while (current <= endDate) {
    const dayOfWeek = current.getDay();
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
    
    if (!isWeekend && !isHoliday(current, region)) {
      workingDays++;
    }
    
    current.setDate(current.getDate() + 1);
  }
  
  return workingDays;
}

/**
 * Add working days to a date (skips weekends and holidays)
 */
export function addWorkingDays(
  startDate: Date,
  workingDays: number,
  region: 'ABMY' | 'ABSG' | 'ABVN'
): Date {
  const result = new Date(startDate);
  let daysAdded = 0;
  
  while (daysAdded < workingDays) {
    result.setDate(result.getDate() + 1);
    const dayOfWeek = result.getDay();
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
    
    if (!isWeekend && !isHoliday(result, region)) {
      daysAdded++;
    }
  }
  
  return result;
}

/**
 * Get next working day
 */
export function getNextWorkingDay(date: Date, region: 'ABMY' | 'ABSG' | 'ABVN'): Date {
  return addWorkingDays(date, 1, region);
}
